"""init

Revision ID: 679a769bc11c
Revises: 
Create Date: 2023-01-07 12:23:39.517802

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '679a769bc11c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_description'), 'food', ['description'], unique=False)
    op.create_index(op.f('ix_food_id'), 'food', ['id'], unique=False)
    op.create_index(op.f('ix_food_title'), 'food', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_title'), table_name='food')
    op.drop_index(op.f('ix_food_id'), table_name='food')
    op.drop_index(op.f('ix_food_description'), table_name='food')
    op.drop_table('food')
    # ### end Alembic commands ###
