"""add created_at and updated_at field for food

Revision ID: 9cedb00191e2
Revises: ec498eaf27dc
Create Date: 2023-01-15 17:53:56.040432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9cedb00191e2'
down_revision = 'ec498eaf27dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cart', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('cart', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cart_created_at'), 'cart', ['created_at'], unique=False)
    op.create_index(op.f('ix_cart_updated_at'), 'cart', ['updated_at'], unique=False)
    op.add_column('cartitem', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cartitem', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_cartitem_created_at'), 'cartitem', ['created_at'], unique=False)
    op.create_index(op.f('ix_cartitem_updated_at'), 'cartitem', ['updated_at'], unique=False)
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_category_created_at'), 'category', ['created_at'], unique=False)
    op.create_index(op.f('ix_category_updated_at'), 'category', ['updated_at'], unique=False)
    op.add_column('customer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_customer_created_at'), 'customer', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_updated_at'), 'customer', ['updated_at'], unique=False)
    op.add_column('food', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('food', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('food', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_food_created_at'), 'food', ['created_at'], unique=False)
    op.create_index(op.f('ix_food_price'), 'food', ['price'], unique=False)
    op.create_index(op.f('ix_food_updated_at'), 'food', ['updated_at'], unique=False)
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_updated_at'), 'order', ['updated_at'], unique=False)
    op.add_column('orderitem', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('orderitem', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_orderitem_created_at'), 'orderitem', ['created_at'], unique=False)
    op.create_index(op.f('ix_orderitem_updated_at'), 'orderitem', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_updated_at'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_created_at'), table_name='orderitem')
    op.drop_column('orderitem', 'updated_at')
    op.drop_column('orderitem', 'created_at')
    op.drop_index(op.f('ix_order_updated_at'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    op.drop_index(op.f('ix_food_updated_at'), table_name='food')
    op.drop_index(op.f('ix_food_price'), table_name='food')
    op.drop_index(op.f('ix_food_created_at'), table_name='food')
    op.drop_column('food', 'updated_at')
    op.drop_column('food', 'created_at')
    op.drop_column('food', 'price')
    op.drop_index(op.f('ix_customer_updated_at'), table_name='customer')
    op.drop_index(op.f('ix_customer_created_at'), table_name='customer')
    op.drop_column('customer', 'updated_at')
    op.drop_column('customer', 'created_at')
    op.drop_index(op.f('ix_category_updated_at'), table_name='category')
    op.drop_index(op.f('ix_category_created_at'), table_name='category')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    op.drop_index(op.f('ix_cartitem_updated_at'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_created_at'), table_name='cartitem')
    op.drop_column('cartitem', 'updated_at')
    op.drop_column('cartitem', 'created_at')
    op.drop_index(op.f('ix_cart_updated_at'), table_name='cart')
    op.drop_index(op.f('ix_cart_created_at'), table_name='cart')
    op.drop_column('cart', 'updated_at')
    op.drop_column('cart', 'created_at')
    # ### end Alembic commands ###
